repos:
# modification
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-toml
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: mixed-line-ending

-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        additional_dependencies: [ "isort[pyproject]" ]

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        args: [
            "--safe"  # don't change AST
        ]

# check
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    -   id: bandit
        additional_dependencies: [ "bandit[toml]" ]
        args: [
            "-c", "pyproject.toml",     # configuration file
            "-r"                        # scan
        ]

# FIXME: temporarily disabled as it fails
#-   repo: local
#    hooks:
#    -   id: pylint
#        name: pylint
#        entry: pylint
#        language: system
#        types: [python]
#        args: [
#            "--rcfile=pyproject.toml",  # configuration file
#            "-j 0"                      # parallel execution
#        ]
